name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run:  sudo apt-get install libpcap-dev &&  go get -v -u github.com/40t/go-sniffer && ls -l  $(go env GOPATH)/bin/

    - uses: actions/upload-artifact@v2
      with:
        name: gosniff
        path: $(go env GOPATH)/bin/go-sniffer
